### ISSUE TITLE
addGraphQLSubscriptions is not a function

### ISSUE THREAD

**Issue by eruby94** [howtographql/vue-apollo#1]
I've figured out 0.8.3 will still work fine, but just want to leave this here to make sure it is addressed.

My recommendation is to fix the tutorial to 0.8.3 until the 1.0.0 release of the package is done, since other breaking changes are likely to occur. Then, update once there is a stable approach to the hybrid situation.

**Comment by Matt-Dionis** [comment]
Thanks for pointing this out, just added a commit which locks `subscriptions-transport-ws` to version 0.8.3 for now which matches the updated tutorial.

**Comment by eruby94** [comment]
Yep, I just saw the approved PR in the docs reflected. Didn't see the edit on github at the bottom of the page on howtographql.

Thanks for the quick fix!
