### ISSUE TITLE
warning message in console after creating a new link

### ISSUE THREAD

**Issue by ldiebold** [howtographql/vue-apollo#5]
I was receiving the following error in console after creating a new link

**Missing field votes in {
  "postedBy": {
    "id": "cj87zsb0ugnx40179lnytjrz6",
    "name": "John Smith",
    "__typename":**

I was able to fix this by adding votes to CREATE_LINK_MUTATION:
```
export const CREATE_LINK_MUTATION = gql `
	#2
	mutation CreateLinkMutation($description: String!, $url: String!, $postedById: ID!) {
		createLink(
		description: $description,
		url: $url,
		postedById: $postedById
		) {
			id
			createdAt
			url
			description
			postedBy {
				id
				name
			}
			// this line wasn't in the tutorial
			votes {
				id
			}
		}
	}
`
```

I'm new to posting issues on github, so let me know if you need more information :)

**Comment by Matt-Dionis** [comment]
Thanks, @ldiebold! I'll post a PR to address this.

**Comment by Matt-Dionis** [comment]
Fixed in this commit: https://github.com/howtographql/vue-apollo/commit/931bdcdbaa96b7fb8f70511f54e0fb62decaa419
Thanks, @ldiebold!
